#index:
#    path: /
#    controller: App\Controller\DefaultController::index

index:
    path: /
    controller: App\Controller\IndexController::index

app_lucky_number:
    path: /lucky/number
    controller: App\Controller\LuckyController::number

logout:
    path: /logout